[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.28.0"

[programs.localnet]
zapcoin = "2dv7D1h2w5QcvMEnB6qqFYSudmb31uyvTowBvLoBcUN9"

[programs.devnet]
zapcoin = "2dv7D1h2w5QcvMEnB6qqFYSudmb31uyvTowBvLoBcUN9"

[programs.testnet]
zapcoin = "2dv7D1h2w5QcvMEnB6qqFYSudmb31uyvTowBvLoBcUN9"

[programs.mainnet]
zapcoin = "2dv7D1h2w5QcvMEnB6qqFYSudmb31uyvTowBvLoBcUN9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
